package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Repo struct{ID int64 `json:"id"`;Name string `json:"name"`;Description string `json:"description"`;Owner string `json:"owner"`;Visibility string `json:"visibility"`;DefaultBranch string `json:"default_branch"`;StarCount int `json:"star_count"`;CreatedAt time.Time `json:"created_at"`}
type Issue struct{ID int64 `json:"id"`;RepoID int64 `json:"repo_id"`;Title string `json:"title"`;Body string `json:"body"`;Status string `json:"status"`;Author string `json:"author"`;CreatedAt time.Time `json:"created_at"`}
func Open(d string)(*DB,error){os.MkdirAll(d,0755);dsn:=filepath.Join(d,"githost.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);migrate(db);return &DB{db},nil}
func migrate(db *sql.DB){db.Exec(`CREATE TABLE IF NOT EXISTS repos(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT DEFAULT '',owner TEXT DEFAULT '',visibility TEXT DEFAULT 'private',default_branch TEXT DEFAULT 'main',star_count INTEGER DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS issues(id INTEGER PRIMARY KEY AUTOINCREMENT,repo_id INTEGER NOT NULL,title TEXT NOT NULL,body TEXT DEFAULT '',status TEXT DEFAULT 'open',author TEXT DEFAULT '',created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`)}
func(db *DB)CreateRepo(r *Repo)error{res,err:=db.Exec(`INSERT INTO repos(name,description,owner,visibility,default_branch)VALUES(?,?,?,?,?)`,r.Name,r.Description,r.Owner,r.Visibility,r.DefaultBranch);if err!=nil{return err};r.ID,_=res.LastInsertId();return nil}
func(db *DB)ListRepos()([]Repo,error){rows,_:=db.Query(`SELECT id,name,description,owner,visibility,default_branch,star_count,created_at FROM repos ORDER BY created_at DESC`);defer rows.Close();var out[]Repo;for rows.Next(){var r Repo;rows.Scan(&r.ID,&r.Name,&r.Description,&r.Owner,&r.Visibility,&r.DefaultBranch,&r.StarCount,&r.CreatedAt);out=append(out,r)};return out,nil}
func(db *DB)CreateIssue(i *Issue)error{res,err:=db.Exec(`INSERT INTO issues(repo_id,title,body,author)VALUES(?,?,?,?)`,i.RepoID,i.Title,i.Body,i.Author);if err!=nil{return err};i.ID,_=res.LastInsertId();return nil}
func(db *DB)ListIssues(repoID int64)([]Issue,error){rows,_:=db.Query(`SELECT id,repo_id,title,body,status,author,created_at FROM issues WHERE repo_id=? ORDER BY created_at DESC`,repoID);defer rows.Close();var out[]Issue;for rows.Next(){var i Issue;rows.Scan(&i.ID,&i.RepoID,&i.Title,&i.Body,&i.Status,&i.Author,&i.CreatedAt);out=append(out,i)};return out,nil}
func(db *DB)CloseIssue(id int64){db.Exec(`UPDATE issues SET status='closed' WHERE id=?`,id)}
func(db *DB)DeleteRepo(id int64){db.Exec(`DELETE FROM issues WHERE repo_id=?`,id);db.Exec(`DELETE FROM repos WHERE id=?`,id)}
func(db *DB)Stats()(map[string]interface{},error){var r,i int;db.QueryRow(`SELECT COUNT(*) FROM repos`).Scan(&r);db.QueryRow(`SELECT COUNT(*) FROM issues WHERE status='open'`).Scan(&i);return map[string]interface{}{"repos":r,"open_issues":i},nil}
